spring:
  application:
    name: observable
  reactor:
    context-propagation: auto
  zipkin:
    baseUrl: http://127.0.0.1

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.micrometer.tracing: TRACE